# -*- coding: utf-8 -*-
"""Datavisualisation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/104Pni_yFwDi9aVW3NjOUKnT51NKfaze0
"""

import pandas as pd 
import numpy as np
import matplotlib as plt
import seaborn as sns

sns.catplot(x="Embarked",y="Age",data=df)

sns.catplot(x="Embarked",y="Age",jitter=False,data=df)

sns.catplot(x="Embarked",y="Age",hue="Sex",data=df)

sns.catplot(x="Embarked",y="Age",kind="swarm",data=df)

sns.catplot(x="Embarked",y="Age",hue="Sex",kind="swarm",data=df)

sns.catplot(x="Embarked",y="Age",kind="box",data=df)

sns.catplot(x="Embarked",y="Age",hue="Sex",kind="box",data=df)

sns.catplot(x="Embarked",y="Age",hue="Sex",kind="violin",data=df)

sns.catplot(x="Embarked",y="Age",hue="Sex",kind="violin",split=True,data=df)



sns.catplot(x="Embarked",y="Age",hue="Sex",kind="bar",data=df)

sns.catplot(x="Embarked",y="Age",hue="Sex",kind="point",data=df)

sns.distplot(df.Age)

sns.distplot(df.Age,kde=False,rug=True)

sns.jointplot(x="Embarked",y="Age",data=df)

sns.catplot(x="Survived",y="Age",data=df)



sns.jointplot(x="Fare",y="Age",kind="kde",data=df)

sns.relplot(x="Age",y="Fare",data=df)

sns.relplot(x="Age",y="Fare",hue="Sex",data=df)

df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Datasets/main/titanic-training-data.csv")

df.head()

df.head(10)

df.tail()

df.dtypes

df.info()

df.shape

df.isnull().sum()

df.describe()